version: '3.8'

services:
  # 1. Database MongoDB
  mongodb:
    image: mongo:6.0
    container_name: reqsys_mongo
    restart: always
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

  # 2. Backend (NestJS)
  backend:
    build: ./backend
    container_name: reqsys_backend
    restart: always
    depends_on:
      - mongodb
    environment:
      - PORT=3000
      - MONGO_URI=mongodb://mongodb:27017/reqsys
      - JWT_SECRET=supersecret_key_change_this
      - GEMINI_API_KEY=
      # [QUAN TRỌNG] Biến này giúp backend biết đường dẫn file
      - BACKEND_URL=http://localhost:3000
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    # [MỚI - QUAN TRỌNG] Map thư mục uploads ra ngoài máy thật
    # Cấu trúc: ./đường_dẫn_máy_thật : /đường_dẫn_trong_docker
    volumes:
      - ./backend/uploads:/app/uploads

  # 3. Frontend (React)
  frontend:
    build: ./frontend
    container_name: reqsys_frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  mongo_data: